#include <string>
#include <map>
#include <iostream>
using namespace std;

int maxNumberOfBalloons(string text)
{
    map<char, int> m;
    map<char, int>::iterator itr;
    map<char, int>::iterator itr2;
    m['b'] = 0;
    m['a'] = 0;
    m['l'] = 0;
    m['o'] = 0;
    m['n'] = 0;

    for (int j = 0; j < text.length(); j++)
    {

        char key = text.at(j);

        if (m.find(key) != m.end())
        {
            itr = m.find(key);
            itr->second = itr->second + 1;
        }
    }

    for (itr2 = m.begin(); itr2 != m.end(); itr2++)
    {
        cout << itr2->first;
        cout << itr2->second;
        cout << endl;
    }

    m['l'] = m['l'] / 2;

    m['o'] = m['o'] / 2;

    for (itr2 = m.begin(); itr2 != m.end(); itr2++)
    {
        cout << itr2->first;
        cout << itr2->second;
        cout << endl;
    }

    int min = m.begin()->second;

    for (itr2 = ++m.begin(); itr2 != m.end(); itr2++)
    {

        if (itr2->second == 0)
            return 0;

        if (itr2->second < min)
            min = itr2->second;
    }


    return min;
}
// int maxNumberOfBalloons(string text)
// {

//     int count = 0;
//     string y = "balloon";

//     for (int j = 0; j < text.length(); j++)
//     {
//         for (int i = 0; i < y.length(); i++)
//         {

//             size_t found = text.find(y.at(i));
//             if (found == string::npos)
//                 return count;

//             if (found != string::npos)
//                 text.erase(text.begin() + found);
//         }

//         count++;
//     }
//     return count;
// }

int main()
{

    cout << maxNumberOfBalloons("ocessgwinhqqhvodyydaklgfzogqtetsyrfaviglhjgvbjcznybioiwqoguodlghwyrggvpvtraenwlqyhwnrkkciehnjgklfxmgyhskgfwmbdcqjncocgoidlwkkgdasbsdrwwgsbouerxtdnxnvkoomfjzhqufwctrwtsueqoyezbzhhhuyypmumevmteurxbkvlmjolmgsqcrxrkyiurypxhskbuhihjwqpiuqzotpjenewvbjtxkjaixkpesneirqpzbesckxxpvhjeolahosmcbwowbikrelhyutokyjdycievpxwtinpkmsetxrbijmbmyoydabeyrhtwlpliiawbuylytuueaqhvsoiqjpvpdhpbwyucsyhbzovlsyqavsjvdrbjtkhijupxsxgmbgsaorwfzfqezicoxxgjbafpwdxgasjsgubzfrvvgykcuzjtnsqtjttklysfgdjwcagstlbmeiwhjrpfhfpdtmohuegkbldltutjzejagtalgiawvpvrykcdrwbgognntdwdeytemiuqyuxytaksjbuxmskaewtamktbvyfwylxyrksiytabcfebvdxfdjvyrllxohwehzjicrrfexcbvjarbncutwwizlbttlijvqrcxkeyzdddiylcctpyjhowrdspigtnehhspvqbiaqccgltlxjxggxwwllfrsygfvzkmdlxnhbijfdwdgwssmnhflodpcfjcqyqengantornzziqvvokbtihketupcibdliwrepgmowikeegqfytufcjqswxadqlujagadqrwkfgciywflvxqktargbhyxnwyfmsmfzhyhakmiqtmembjttzkizmgghsbzowdmyedkjbykhcqmiclofkpycfpenmqivxlqklscjhquwlwuoxqykdftvbheoifuhpuzkaarojmxmrjkcoilhbiiryvqoalwpqnafsrhywbtxhbaikexmalkvyxbvoyrbmukgypxohmgoolmgltxaqhqtbljscaccnlhsypjlyawdvcpjpdgxpvgrjyzxegnvkkwojgukazbvsmxwvbqrcnvraxxpaobriudpjlzklmgmpeaqyisdzwmvgpvvlcqkpxjlubyeogjbasenoiccedilbxhurntonkqbgidjfwoieoznmaxtkjjzokciykdghngttidjcfhszrfljlwnuvvkiiwjdmwtpzkfctvhdzsrublceodzlptppsbglbzkqsfgfbcunqstmrlktulyjzxkdknqgsbqrghpkuxxfayzmfjkgxzavexwafeqpqjdakadgqeghikszavxgotdlspgmjozwmqrlxbazuoywhxtpwwicgupetcnawyhevfovabbdyzeeeiqshlmubrfzcuvxoykunxmxhdzdeqjpjoaseqqpvsicoigjasyaqjqjxlstvnkqtxydqhhulyrmzsbjcwqwydqmhdrqoewptgpbrjaxasxiwyicfppkilclejugkpdenixdikcfxxoizanilczajdyiqtwbqggbdtfojxcdfsqmicajnmiivwjiclzrqiosnogpyataotycjilbwradtuhksujlphjrartnnhnumyshtibzucazluridpsyyybnawuvbspxtgagtstascpalxsnjbagpnnmqyjdrahaxplgfkovmxtwamzpqhewnewhmilehmdkochyahoyatyyqtewbffhmzdxuuauhbxtjykodjjnuzlwtjfqdkusauavvfelnhtsdxysvhpyxclfbrmqkwvnimgeeyufubrzmqpndglamhqwaeivdmxmzlrvjxwdmrgzyoxxqyxzhofqkguzhpxjtuwllabeyvjlbcpyiczpeuyvcwwxhfllshuqojiocrfwqppajpxitmitwdioylmoovofofqsmsxzzxtzlbwxytbbrknlnorlsbvvdzixokxfrocwrpmuvcxzsweqcezqhsodzpmalxjaidgccoufmfivcaaxemziawirtoikbkegcvvougwgknjxprkcrfyywsyqxzntxchpegsaoyxickpvvtmgwhqqzeutohvhvexkahmfzmskivloojsrktvahfzgxobmnjzgwfrzzdbyabttrpuqcfynbzzstxjqwwdxactzuynabywypzbsdqndsluafqwlhifykhostfewabozuujhryyrwllpcrpdbnqsmxdkjajwrkiyjammqtehgyyrlmoglfqsrjrlcxdyieqnovdhkzduepspufpznglztiulzajszgkqdkptkqqxatvyfjviejyidoetwxarpqqatwrlmvgnyhhsevialwkvjrnkboivzmjphzjwlzezgdytbwdkivwmxzngapjfeenwokpszxqvwjsprveohketynvpehxuehzurasfhunwwiusxagvrbtcktptsipzsdtvzfuaxsgbvkgrdjbdgwdbxksdqpsawswjwarjgdprfthtjztjrxjdqnbeqffgrxrqzxuqcspsfedpnxojbtatdfcmpuwnucpchvzkwzjrpghsxjlgoececrljsfbjzppcwmuuefifxgltdwtqycvhkvbjjinefpzolaqdtbmiulinslecmctmhuiplfvvcudtskvgqbwtlwcaymkcxsmigmahsfpnpelakgeagoaddssahmdfozrlpspealtmoketskgfjfsloognimwttbdjeaymfottqubuwpggcigwmdzyfvsjrtkbvxffksxfzlqvfkszcbcoxipildhlzbmgpgllcfomwsdzfcaxrzkswsiwrxqhuwxvplvgaexawqehnokrpkpqfdjthwsyskjjhmelbsesctgghyekuuzovhhqfjzosuravbfnziipelrpkxiiuzdukkhcvenluaiyyiguuifsxbyvqhzqatyhksvxiyhlupfasvxtqplzgovaudbxqsupazqzcnpadtbnfxisotuqzbofflvvzwgmvvjigieqrgcvddzpttwxqvmxvcunehoqodrjkalltntfhmxwpahcyqajmdozrnuuempuipxpvwcpvetjeociaubajklotiydbvllwsixlfpoxsukmymjzzsywmaqibizmuymutndpvquismcxcctgjngacngpzscbtapvztetjbzpydqaabquonwucxkczaliouiglegbwlonhowxlmmoqnmqmwigyqwvobdtorrxpfvnnhctsajhsknyspyvrxuprlmqounwqfcewgwihfejsjhfgjadfrxivpiorjmiupvirupbrqfqslicczbdsscoevzjhxqyusztcgxrttbiysskjkyeovcjkezxnzfynlrthkqyksnjaskpiaposeiqikuhuimcjdmjwdyupegtdzvrfxklbvlrxwavvphxapgdzgwrhsfuvwmyrmqykolsyrdcugebnyhvpcilhwokmogkbgwjhnpjpglvfyykjdycylwntnqfbtbwquimtwczqlvizsnrcibyyyfyxecmyajvnpdytehlceqymewfxgcnyclubilxivytkrjbvtgzkyanszxkjkpetpvoqxglhzfysbdjyfbufpluaryqqobduqcpvswgbwlnfihzwngolpfqorlzzvdjniridcpqviigkjhcfmnyysegfloammqhwlkkrcxcfuprpyzfoalvcgibllvjwjyvotzkzphtkyrqbcbwhdlemmiwnjuzxnpqzfnzumykeokfelsfurconxmodcgcdczakrwbrejopnooahjyldygorwrsipegstqqyxxbkzuqqcztpwgmjupbcibkvgnbvmoevskekfmrowovisrnminwdsacdjdxupvpabbeqrzitdvmvnifagyirtqomaqvefipviekgnvqpbkaglaugjnqgxwycjrvndrssfygrqxxgswqotzcdozherdkgworjgcaacxrzxdaphhdspxwlflcrgvosoxktgenpgxsisowhvonvvbrplskvnvvizfvlduanzwbhxmayebjmtayykhezhxwosffnytjguhcfslztimpmjtmvaetiujscchtgucnrhplxwhvfyizpppunvvpyojjkaizoxehuzpxnyiukkzogvusptbjkzzgfqgefmnzpouyuxspwqilijdhoirojbvbiaelnpwgqvowlyirkutbzljpqeixndoyvqrzbabxxuxqzjxqtbnwshyfeaiymoplmyywsixsrcneiosszwikxmswocxbsctsiygjughgjgkkbmupwvpzrawtayvcirsllgyamboywxydtqlecnskmajfakwafbhedzrrpjmbfmpdjeqivurcvcaksjztaknbcpoikgqxosgfwzexfcgxogsdkceftvpvhfrocijferkpwdoeyiszdgjlkmeqzhuizcpjtkpoewxftnyqubfsavlskiipzbymqmokprtvriditvsnhqtytiplzxpmfodgetqmzrymdoclczibtwlyhwugoazshahsstaaqvdvdaqjlindxcpdhbnkpmmhxfcyywuxtezsqcoiualuvcrvknlufrmgmnixtoabgwpsouwghkwweoidfcubrmkexpvopubxragcblvvxkbuvjuazmthxczihjudbqadoxypebmgfiprheeodcazrvqkwdjawjihcvduhdcjgthhsjysiogzsmwufpixeszokvsqhdukxfbbqnproyqtcgtchdjerigygkjdvjtaynlsmiapdujanolompmqkjcmvgdzdvdjxtsxvkmthrppdzlnyvixsuinsdxmrjrohqzlwiwebvaqmohjuzsvtopfgzwvgnwjsypywzdexvqvdgfuxaxlbghcsrtrixrxobealdwbuommrvhceaxeedamounffchaoxupdqmxmcxdfrfspmrhsckptozufkvzwxutdwieachemtwtfdldjogqlpplcbmchuwlduwwegwjcpjvecowvmuvbsiezgjpuvwjoldgefmkjezipftifspgpmuqogizqzorkonnqbszpvohvfijitxeybrtatrjutyixseftmizodjwcxbtyfuyhtknjshidogsjpnoobfpzmzbziytskhwimokozytmmlmgzcjczthptqkrsbotwiainoyoptidrkqzteqfhbczujpddedhccceezlvtsmhzmaymdurorjrvkteymcjbdxfslkjxhedsszqbkxjuadzfjqczgescdfghlyyvrqdyzregfkvghxvvepzdafsshiuvcysxcvptdtojvjeedmpyeexkrozfffywijmgwjrluieousjcgusfloeskhbizvyfghrufhkemhqeqrywjagnthrsarhvipmsmaylqrjqscgnprfcfefgrbelezrbbaqoskesiiwjzgjpeaiintzrthxgihabmszzwedpibegcbcvjaayvweifuqzxtcxktzzddnxnxuqgqqpxolyieibhurxfzodymdfjffhhrkswjdgzwbzojstoblgnpgkxavvlkjfaapvnbhbgipilmpxdcdodunhlnfuqqckyykzslqdzflgigtdhxlcpkncbhotislurytshmgbzrwtsiemyilasynqonemvbuewadkgubjnekbtricfuxdglszrkiwqirfmyoxyqkeedheudzucqxcyjxaklrbvctssphyqoovcezywscongzukadxexpcyqokjmocshktrenplrrfmeutoyiuciunjdmmdemfqpidktclobpoakeghowdbxjjpzgpujymusepqadzhbvqdsjyzhcsadyoekaaopqsvspiicvqohtjlluwedvunbwenmldqonbkosmahjtqhxcbtczcotjunuvszhkdfjcexpauvgszhqxvnywhsazydlcemoibcvldagaxztomivihxvuboozbyfqqhdgzanlzumjmpjhwwgnyjzffsjuatbhqvkvdwfydnivlrgqucoezradenlndukstfcqdediijupumbpoqnxncwxvzlcmyehxiqkugtadkyhiouaskkvcwywfcmfuwpdrvphzzbrnetpzdwewvddhujinladpqyszpmybpmojruhhqzdvlcyqbealbgxglaxqltgsqvogekoprecnziakztikulgfwrpjqxbdynfjwwbezttqzzuzyjxnvxylutzqgvqesszztismzcpowuhbopkwcrypudccxztlgzusknrxrpdftaaznomsaosfggrlcvgiwoimzwemnyrhtbweakbgxjyilhcupwpvwcpwsuqiylonvkayefoaomtfjqqrwxbazhftchkcszbckrutqmuqyyyilsaydzxtouztdykrugkwtsuhmuvovrqkeexmkofzferzovhaggdiibcsxwmmblugzefjroofibsgwlamnlbomcdbjpzzhkrmzcmfkqywzffgfaohacegerrmfohlewuphegvugzkijwquxoddostksyrqfveoibmvyhvfcqsauretydlnnyfjkowspmjsxrphcnghbbjqckrfhugsyzgqqigdikftpfcpdpmnsdwfitgtradihpcjaiczcsivpjctdvzpreivbkibaktqrxjtllzgnwkrjvlbjgmwlefafziueoqfredxfpghjoknttmjyytpuuqbtxhisgtleksolfpwndzxewgqnobmuwrqgqijgkxbpihmzawzjnmxulgmmvfwpppulpsqiyvfctmqarlnhsxpwmqlzivmwleszjuiupjozplohhqbpxixbhniwmyhcyhukflbfhwcqsaccrldihikbrnnqfmzshimkmvhxcsvwlirgqupzwawxdmlspdfvkyrnekrlaxkogscszpywbkpctdzukcepxnyduesvroxddlconynioupkmyegtapimpbvazlwdqfqgfcxmiaosbmqjdixlbdhilqnvtfmxyaquxzisufpffeznwudglkbwmcvnoazwyhvhjcgokeomjodysplrhvmwbnniedakttshotjrcienaeevqsidabhgusfxjdpgncnskwkccxahnzldsykvewarbshensxldsjljmttcheasmtipnpkkqaozuxghphelomfbfparyzupftxeojyqozqcxddllxibjmwrpnnplwhttkjerirnlsmpjmwxrpnoepjatupljtzeqsgjrjzvjleqsujflkmclejgrmfehtyyxsdziyzsiiksvwtqxaxnsqkdrgutphqdlkywlxfkhpywcbjpwkucoiaumtpjunklyegybsnpcigayassqgzggoxfmvkejnikowkpursfmfdiukmgultpcubecqgexckfkevqvwmjujfkobnlgadpyfcqueggmjztfbplsdryznqwfuuweuluojbtionznjvtukpiwtyavndxeqauumovuqkejuymeytswzfxbitzbyxmkgihezffcfqhbholiezebukamxgronjtdilxqzgyfntbphqnbwtffptovaafkgxperawspcxpvtfvlccndufznqambzzenvaqbyjjfjxmmkecrhfpqdflqcaovohwregoeqmqyqdozojpqwtyzibpcxinfmmnpsfovlqyexcpeoidpofzdmjtwjynwcdvhlxbuavhkkerdnckwppbbstkolkeqjhrslwyzzqwxfidxhcyrvrrrntaywjfawhbwqviwjtqztzicmzytsoelxtuetzvffdrpnrbuibvxbgsqbgzbrpjtgcifceeyijsjsjhgsfwjmcsfptjltuhnvfpuyqdwnyygrddaiguuhfpyehytsfmzmvlmadqpjjgusrquucsvllncvsgnrtyuymmgtbvgoxzobuetvggqyraqyiiwsnikipfscpjgxxluzwerocmkygsreitiwdosxgyaffyaglbfclleujkuanmuiccyznmuedslcoztfgemlcolabiigvtysgddufcwzfdtkjgiidkxipjjyvmwoojgajpguttcszcyjekshdvxpxufdkyuxkhtcfdphcmgqmiqyxysqdudnssmtyshprawntyykswhkpsjrrgrfiynrgmskvbcyossdhxfohonndcuwurpqvvyiesdayphdgmftuuetqawgznciriffodrfsrxomrjelefhctyhycrnukvpgqxlzcklbrrczqluiaolshjmznqhwnvqpqtqbghcnwxbfkkgovpwjnzclohjuizbpabpcygjdyyruelvbdwttahkrqlhngoweczaaxsvagekkeckfilybgpkogabiajejzcvsvnwlhotqonztoyuhtnddalcqxjwzngwasfxtsqufygwdslfxefdylcbztwlbmtvywescdpsnpvbuankbtgsemfxzwsdudsclrsgtxtsialxmlbvwhsiqhpcngnpmnonplehqtwyoboiszyhrhrkdcnxhymwhrklalhtehacreupiysfzlmedbwvqpuuvtznrxnooksgratgvujgygptoeqwvgxcqoxcqvlenjqhfryfbduyqsydoaznttvocdwjfyswpnyitqlnpqnkbqyrosdmgaimvyyztppqpwlmbgwwkmalhlxyrlyvmhnpgcfuycaxpsfxwzlxnsmwswsbjqayekcduyxgocjqovjpmmcxqhkpxqgrtkkcsdkyxavdwpgemffekwcsgiouupwyqoayoyyzepoquwrvorjkithzzncqihzqarlaboqomwgpjfnvqfbgjdfuvnpxyfiyegvtpblzkwsbedmexiwstareyhjfcvsoxcnzcduemofvceekihujwwslratleebetbmsdaccbweuubpyndrrxolbwpmaertszgrpgmxvdwilftpqhipcdboqebrcgyvdvmgpenisxaakrnxdxzcyzyczqqdxgpwvhrfmxrsyxrcrkymtcmtipbrblcugkgzvcaxszhluswpebavwrizhmcquklaftiirnaujavopfucsucyixtalwphrxddmxreuktxhujacknrwesjirromdgaojdlkntjuxguzdmhpoqltwmygxvfwkprflcvlizqanyjkchhbxahibvufaxgunzdwqulemknsfxtpivbwqzcjsygbytyofkiygsuyyebfhnqmfjlicohkdxtxgtxogqntllffxxjqiwjdafbwloohvpyoldupmztdfntlvxrykdkvdjioxtocuscpnkdiprlzbuezrcuafpqbgbmfmaqvhsdsatombubnpnhcvvsinipacddhndiqfpfozswozcxxusrwwimiupmjsuaciyjlxaxfqaqknlhvjrqraqghmjvaduiktldklsnggqqooyilffakfoqqkicujtlingmgmfwexzdnhlanjqqbkhwbvnqvqebwmsnpltymqxmctskdttppevxrzasnxnalfaktzjruuhbqlqmbrujzeprtuuyhwdqtylvrylhzdvzytakoucaklxtkbboexykpwiwhmvwadedlmpdmvjkfjqxoxrtrbqmahwiylnufshxqtbclqltxxuwdhtgpwojhgzrlfsfvkwadnzajbexmsftgarzmulrrywkkjqzauywfljfvbbwzkhpdftpwtwzybrzjmhmclwpqkqovocbhcsfqitibwyqjkjpumlpqaumrxttgywtylmzimuwwzaazuocprbbjgelpfzzrmenkxdwvmxvptrvufgpjqxwdwhjrzsmsgrkrxvxmtduarmszymigojuedttkvsfxoatmcelsutzrexoqvrwcounprkcyvoparvzpjczdeqmswvgjhautdwxbsvfugmywyegekbisxseaxctdymbbyfsxbhfokxnqatoresqmpjcktygh");

    return 0;
}